import { MartechTool, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'seo', label: 'SEO & Content', icon: '🔍' },
  { id: 'social', label: 'Social Media', icon: '📱' },
  { id: 'crm', label: 'CRM & Sales', icon: '🤝' },
  { id: 'ai', label: 'AI & Automation', icon: '🤖' },
  { id: 'analytics', label: 'Analytics', icon: '📊' },
  { id: 'ads', label: 'Ads & SEM', icon: '💰' },
];

export const MOCK_TOOLS: MartechTool[] = [
  {
    id: 1,
    name: 'GrowthMetrics AI',
    category: 'analytics',
    type: 'SaaS',
    short_pitch: 'Analisi predittiva per moderni team SaaS.',
    software_description: 'GrowthMetrics AI sfrutta reti neurali avanzate per prevedere l\'abbandono dei clienti prima che accada. Si integra direttamente con il tuo processore di pagamento per fornire punteggi sulla salute dei ricavi in tempo reale e flussi di lavoro di intervento automatizzati.',
    features: ['Previsione Churn in Tempo Reale', 'Previsione dei Ricavi', 'Analisi delle Coorti Automatizzata', 'Tracciamento Eventi Personalizzato'],
    integrations: ['Stripe', 'HubSpot', 'Salesforce', 'Slack'],
    pricing_model: 'Paid',
    pricing_starting_at: '$299/mo',
    price_numeric: 299,
    location: 'San Francisco, CA',
    logo_url: 'https://picsum.photos/seed/tool1/200/200',
    cover_url: 'https://picsum.photos/seed/cover1/1200/400',
    website_url: 'https://example.com',
    contact_email: 'sales@growthmetrics.ai'
  },
  {
    id: 2,
    name: 'ContentFlow Pro',
    category: 'seo',
    type: 'SaaS',
    short_pitch: 'Il calendario editoriale definitivo per team ad alta velocità.',
    software_description: 'Gestisci migliaia di contenuti con facilità. ContentFlow Pro fornisce una rappresentazione visiva della tua intera strategia di contenuto, dall\'ideazione alla distribuzione.',
    features: ['Builder di Workflow Visivo', 'Ottimizzazione Contenuti AI', 'Programmazione Multi-canale', 'Audit SEO Semantico'],
    integrations: ['WordPress', 'Webflow', 'Ghost', 'Medium'],
    pricing_model: 'Freemium',
    pricing_starting_at: '$0',
    price_numeric: 0,
    location: 'Londra, UK',
    logo_url: 'https://picsum.photos/seed/tool2/200/200',
    cover_url: 'https://picsum.photos/seed/cover2/1200/400',
    website_url: 'https://example.com',
    contact_email: 'hello@contentflow.io'
  },
  {
    id: 3,
    name: 'OmniConnect CRM',
    category: 'crm',
    type: 'Enterprise',
    short_pitch: 'Piattaforma dati cliente unificata per vendite omnicanale.',
    software_description: 'OmniConnect abbatte i silos tra i reparti fornendo un\'unica fonte di verità per ogni interazione con il cliente attraverso canali web, mobile e offline.',
    features: ['Vista Cliente a 360 gradi', 'Lead Scoring Automatizzato', 'Creazione Segmenti Dinamici', 'Accesso API Enterprise'],
    integrations: ['Shopify', 'Zendesk', 'Magento', 'Twilio'],
    pricing_model: 'Custom',
    pricing_starting_at: 'Contatta Vendite',
    price_numeric: 1000,
    location: 'Berlino, DE',
    logo_url: 'https://picsum.photos/seed/tool3/200/200',
    cover_url: 'https://picsum.photos/seed/cover3/1200/400',
    website_url: 'https://example.com',
    contact_email: 'enterprise@omniconnect.com'
  },
  {
    id: 4,
    name: 'SocialPulse',
    category: 'social',
    type: 'SaaS',
    short_pitch: 'Ascolta internet in tempo reale.',
    software_description: 'SocialPulse utilizza l\'analisi del sentiment per monitorare le menzioni del brand su milioni di fonti digitali, consentendo ai team di marketing di reagire istantaneamente a trend e crisi.',
    features: ['Analisi del Sentiment', 'Alerting in Tempo Reale', 'Identificazione Influencer', 'Benchmarking Competitor'],
    integrations: ['Twitter API', 'Reddit', 'Instagram Business', 'Discord'],
    pricing_model: 'Paid',
    pricing_starting_at: '$99/mo',
    price_numeric: 99,
    location: 'New York, NY',
    logo_url: 'https://picsum.photos/seed/tool4/200/200',
    cover_url: 'https://picsum.photos/seed/cover4/1200/400',
    website_url: 'https://example.com',
    contact_email: 'support@socialpulse.com'
  }
];